server:
  port: 9999
  error:
    include-message: always

spring:
  jpa:
    show-sql: true
  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  flyway:
    locations: classpath:db/migration
    mixed: true