server:
  port: 9999
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      auto-index-creation: true

jwt:
  signing-key: ${JWT_SIGNING_KEY}