server:
  port: 9999
  error:
    include-message: always

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  flyway:
    locations: classpath:db/migration
    mixed: true