server:
  port: 9999
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      auto-index-creation: true

okta:
  oauth2:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    issuer: ${TOKEN_ISSUER}
    audience: ${ACCOUNT_SERVICE_URL}