server:
  port: 9999

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: emporium
      auto-index-creation: false

logging:
  level:
    org.springframework.data.mongodb: debug