server:
  port: 9999

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      auto-index-creation: true

jwt:
  signing-key: eHXcK2RfLg55yYqh