apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: account
  template:
    metadata:
      labels:
        component: account
    spec:
      containers:
        - name: account
          image: scarron95/emporium-account
          ports:
            - containerPort: 9999
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DATABASE
              value: account
            - name: CLIENT_ID
              value: 0oa2a8z3bC6EayDaI5d6
            - name: CLIENT_SECRET
              value: 4iGDK_3_44hz_faHJPE_CJhqWxGdemlWiolZvbBa
            - name: TOKEN_ISSUER
              value: https://dev-4423593.okta.com/oauth2/default
            - name: ACCOUNT_SERVICE_URL
              value: http://localhost:9999