create table account
(
    id               bigint generated by default as identity
        constraint account_pkey
            primary key,
    username         varchar(16),
    name             varchar(32),
    surname          varchar(32),
    patronymic       varchar(32),
    email            varchar(128),
    password         varchar(16),
    photo_storage_id varchar(128),
    created          date,
    updated          date
);