server:
  port: 9998

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: auth

jwt:
  signing-key: eHXcK2RfLg55yYqh

personal-area:
  host: ${PERSONAL_AREA_HOST}
  port: ${PERSONAL_AREA_PORT}
  path: ${PERSONAL_AREA_PATH}