server:
  port: 9998
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DATASOURCE_USERNAME}
    password: ${AUTH_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  flyway:
    locations: classpath:db/migration
    mixed: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    confirmation-url: ${MAIL_CONFIRMATION_URL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

services:
  account:
    registration-url: ${ACCOUNT_SERVICE_REGISTRATION_URL}