server:
  port: 9998
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      auto-index-creation: true
  security:
    oauth2:
      client:
        provider:
          emporium:
            token-uri: ${OAUTH_TOKEN_PROVIDER_URI}
        registration:
          emporium:
            id: ${OAUTH_REGISTRATION_ID}
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            authorization-grant-type: ${OAUTH_GRANT_TYPE}

  mail:
    host: smtp.gmail.com
    port: 587
    username: emporium.email.confirmation@gmail.com
    password: Emporium2020
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  signing-key: ${JWT_SIGNING_KEY}

url:
  personal-area-registration: ${PERSONAL_AREA_REGISTRATION_URL}
  email-confirmation: ${EMAIL_CONFIRMATION_URL}