server:
  port: 9998
  redis:
    host: localhost
    port: 6379
  error:
    include-message: always

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    confirmation-url: ${MAIL_CONFIRMATION_URL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

services:
  account:
    registration-url: ${ACCOUNT_SERVICE_REGISTRATION_URL}