server:
  port: 9998
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    confirmation-url: ${EMAIL_CONFIRMATION_URL}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
okta:
  oauth2:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    issuer: ${TOKEN_ISSUER}
    audience: ${ACCOUNT_SERVICE_URL}