server:
  port: 9997
  error:
    include-message: always

spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/ads
    user: postgres
    password: postgres
    schemas: 'public'
    locations: 'classpath:db/migration'
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ads
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: /open-api-definition.html
    operations-sorter: method
  api-docs:
    path: /api-docs